services:

  mysql:
    image: mysql:8.4
    container_name: pos-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    networks:
      - backend

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  app:
    build:
      context: ./app

    container_name: pos-app
    restart: unless-stopped

    environment:
      APP_PORT: 3000
      DB_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - frontend
      - backend


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pos-phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:80"

    networks:
      - backend


networks:

  frontend:
    driver: bridge

  backend:
    driver: bridge


volumes:

  mysql_data: